version: "3.8"

services:
  frontend:
    build: ../
    volumes:
      - frontend_nginx_config:/usr/share/nginx/html/
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  frontend_nginx_config:
    external: true
